const fs = require('fs');
const file = 'd:/Local/Development/github/OtherNitx/NitxUI_environment/Nitx-Ui/src/components/spaces/MembersAndNumbers.tsx';
let c = fs.readFileSync(file, 'utf8');
c = c.replace(/<svg[\\s\\S]*?<path d="M21\\.2[\\s\\S]*?<\\/svg>/g, '<HugeiconsIcon icon={Refresh01Icon} />');
c = c.replace(/<svg[\\s\\S]*?<rect[\\s\\S]*?<path d="M4 16c[\\s\\S]*?<\\/svg>/g, '<HugeiconsIcon icon={Copy02Icon} />');
c = c.replace(/<svg[\\s\\S]*?<path d="M10 13a5[\\s\\S]*?<\\/svg>/g, '<HugeiconsIcon icon={Link01Icon} />');
c = c.replace(/<svg[\\s\\S]*?<circle cx="12"[\\s\\S]*?<\\/svg>/g, '<HugeiconsIcon icon={Cancel01Icon} />');
c = c.replace(/<svg[\\s\\S]*?<path[\\s\\S]*?d="M0\\.879331[\\s\\S]*?<\\/svg>/g, '<HugeiconsIcon icon={Delete01Icon} />');
c = c.replace(/import \\{ Copy02Icon, Tv01Icon, Key01Icon, UserAdd01Icon, MoreVerticalIcon, Search01Icon, ArrowDown01Icon, Settings01Icon \\} from '@hugeicons\\/core-free-icons';/g, "import { Copy02Icon, Tv01Icon, Key01Icon, UserAdd01Icon, MoreVerticalIcon, Search01Icon, ArrowDown01Icon, Settings01Icon, Link01Icon, Cancel01Icon, Delete01Icon, Refresh01Icon } from '@hugeicons/core-free-icons';");
fs.writeFileSync(file, c);
